name = "Phlegraean-Fields"
app_id = "677abfcf-1e51-4a05-ab17-a0bcda3ebce2"
app_url = "faa06204-3bfd-4de8-bdac-24d810199848"
team_id = "2f43a1f4-da2e-46ae-80f6-e7b242bea2cf"
team_name = "Marco Tamburro's Team"
